apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx3
  name: nginx3
spec:
  volumes:
  - name: myvolume
    configMap:
      name: cmvolume
  containers:
  - image: nginx
    name: nginx3
    resources: {}
    volumeMounts:
    - name: myvolume
      mountPath: /etc/lala
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
