apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: helloworld-configmap-volume
  name: helloworld-configmap-volume
spec:
  containers:
  - image: gcr.io/google-samples/hello-app:1.0
    name: helloworld-configmap-volume
    ports:
    - containerPort: 8080
    resources: {}
    volumeMounts:
      # Set Volume Name
    - name: my-config-volume
      # Volumeをマウントするコンテナのファイルパスを指定
      mountPath: /my-config/TEST_ENV
  volumes:
    # 作成するVolume名を指定
    - name: my-config-volume
      configMap:
        # configmap名を指定
        name: my-config
        items:
        # Config内にあるKeyの名前を指定
        - key: TEST_ENV
          path: keys
status: {}
