apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  initContainers:
  - args:
    - wget
    - -O
    - /work-dir/index.html
    - http://neverssl.com/online
    image: busybox
    name: busybox
    volumeMounts:
    - name: vol
      mountPath: /work-dir

  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    resources: {}
    volumeMounts:
    - name: vol
      mountPath: /usr/share/nginx/html
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: vol
    emptyDir: {}
status: {}
