---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mypvc
spec:
  volumeName: myvolume
  storageClassName: normal
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi

