---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sidious-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 200Mi
  hostPath:
    path: /data/mysql
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sidious-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  volumeName: sidious-pv
  storageClassName: manual

